//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WindowsFormsApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BDGUSTAVOEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BDGUSTAVOEntities object using the connection string found in the 'BDGUSTAVOEntities' section of the application configuration file.
        /// </summary>
        public BDGUSTAVOEntities() : base("name=BDGUSTAVOEntities", "BDGUSTAVOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BDGUSTAVOEntities object.
        /// </summary>
        public BDGUSTAVOEntities(string connectionString) : base(connectionString, "BDGUSTAVOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BDGUSTAVOEntities object.
        /// </summary>
        public BDGUSTAVOEntities(EntityConnection connection) : base(connection, "BDGUSTAVOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIOS> USUARIOS
        {
            get
            {
                if ((_USUARIOS == null))
                {
                    _USUARIOS = base.CreateObjectSet<USUARIOS>("USUARIOS");
                }
                return _USUARIOS;
            }
        }
        private ObjectSet<USUARIOS> _USUARIOS;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIOS(USUARIOS uSUARIOS)
        {
            base.AddObject("USUARIOS", uSUARIOS);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDGUSTAVOModel", Name="USUARIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIOS object.
        /// </summary>
        /// <param name="uS_ID">Initial value of the US_ID property.</param>
        public static USUARIOS CreateUSUARIOS(global::System.Int16 uS_ID)
        {
            USUARIOS uSUARIOS = new USUARIOS();
            uSUARIOS.US_ID = uS_ID;
            return uSUARIOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 US_ID
        {
            get
            {
                return _US_ID;
            }
            set
            {
                if (_US_ID != value)
                {
                    OnUS_IDChanging(value);
                    ReportPropertyChanging("US_ID");
                    _US_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("US_ID");
                    OnUS_IDChanged();
                }
            }
        }
        private global::System.Int16 _US_ID;
        partial void OnUS_IDChanging(global::System.Int16 value);
        partial void OnUS_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String US_LOGIN
        {
            get
            {
                return _US_LOGIN;
            }
            set
            {
                OnUS_LOGINChanging(value);
                ReportPropertyChanging("US_LOGIN");
                _US_LOGIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("US_LOGIN");
                OnUS_LOGINChanged();
            }
        }
        private global::System.String _US_LOGIN;
        partial void OnUS_LOGINChanging(global::System.String value);
        partial void OnUS_LOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String US_SENHA
        {
            get
            {
                return _US_SENHA;
            }
            set
            {
                OnUS_SENHAChanging(value);
                ReportPropertyChanging("US_SENHA");
                _US_SENHA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("US_SENHA");
                OnUS_SENHAChanged();
            }
        }
        private global::System.String _US_SENHA;
        partial void OnUS_SENHAChanging(global::System.String value);
        partial void OnUS_SENHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> US_CADASTRO
        {
            get
            {
                return _US_CADASTRO;
            }
            set
            {
                OnUS_CADASTROChanging(value);
                ReportPropertyChanging("US_CADASTRO");
                _US_CADASTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("US_CADASTRO");
                OnUS_CADASTROChanged();
            }
        }
        private Nullable<global::System.DateTime> _US_CADASTRO;
        partial void OnUS_CADASTROChanging(Nullable<global::System.DateTime> value);
        partial void OnUS_CADASTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String US_FUNCIONARIO
        {
            get
            {
                return _US_FUNCIONARIO;
            }
            set
            {
                OnUS_FUNCIONARIOChanging(value);
                ReportPropertyChanging("US_FUNCIONARIO");
                _US_FUNCIONARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("US_FUNCIONARIO");
                OnUS_FUNCIONARIOChanged();
            }
        }
        private global::System.String _US_FUNCIONARIO;
        partial void OnUS_FUNCIONARIOChanging(global::System.String value);
        partial void OnUS_FUNCIONARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> US_CONSULTOR
        {
            get
            {
                return _US_CONSULTOR;
            }
            set
            {
                OnUS_CONSULTORChanging(value);
                ReportPropertyChanging("US_CONSULTOR");
                _US_CONSULTOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("US_CONSULTOR");
                OnUS_CONSULTORChanged();
            }
        }
        private Nullable<global::System.Int16> _US_CONSULTOR;
        partial void OnUS_CONSULTORChanging(Nullable<global::System.Int16> value);
        partial void OnUS_CONSULTORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String US_PERFIL
        {
            get
            {
                return _US_PERFIL;
            }
            set
            {
                OnUS_PERFILChanging(value);
                ReportPropertyChanging("US_PERFIL");
                _US_PERFIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("US_PERFIL");
                OnUS_PERFILChanged();
            }
        }
        private global::System.String _US_PERFIL;
        partial void OnUS_PERFILChanging(global::System.String value);
        partial void OnUS_PERFILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String US_EMAIL
        {
            get
            {
                return _US_EMAIL;
            }
            set
            {
                OnUS_EMAILChanging(value);
                ReportPropertyChanging("US_EMAIL");
                _US_EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("US_EMAIL");
                OnUS_EMAILChanged();
            }
        }
        private global::System.String _US_EMAIL;
        partial void OnUS_EMAILChanging(global::System.String value);
        partial void OnUS_EMAILChanged();

        #endregion

    
    }

    #endregion

    
}
